// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-SnhcB0txy4Vz1_-goOdxUoxrYjFYhVk',
    appId: '1:198216456271:web:912d173937e653302a723a',
    messagingSenderId: '198216456271',
    projectId: 'stockcito-eb381',
    authDomain: 'stockcito-eb381.firebaseapp.com',
    storageBucket: 'stockcito-eb381.firebasestorage.app',
    measurementId: 'G-4HEM893LKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ-8cnzWRVU2lDZwtI8pzpMbhpuM8YP8M',
    appId: '1:198216456271:android:3f3faf9d32aca9992a723a',
    messagingSenderId: '198216456271',
    projectId: 'stockcito-eb381',
    storageBucket: 'stockcito-eb381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADSxzuAfMnenwg1b9FgBgu6ekyMWs3YBs',
    appId: '1:198216456271:ios:fb91568abcc410f22a723a',
    messagingSenderId: '198216456271',
    projectId: 'stockcito-eb381',
    storageBucket: 'stockcito-eb381.firebasestorage.app',
    iosClientId: '198216456271-5l55vptssk6v96ffdk30l59a7c7ippnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ricitosdebb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADSxzuAfMnenwg1b9FgBgu6ekyMWs3YBs',
    appId: '1:198216456271:ios:fb91568abcc410f22a723a',
    messagingSenderId: '198216456271',
    projectId: 'stockcito-eb381',
    storageBucket: 'stockcito-eb381.firebasestorage.app',
    iosClientId: '198216456271-5l55vptssk6v96ffdk30l59a7c7ippnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ricitosdebb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-SnhcB0txy4Vz1_-goOdxUoxrYjFYhVk',
    appId: '1:198216456271:web:539d6e8763c27c112a723a',
    messagingSenderId: '198216456271',
    projectId: 'stockcito-eb381',
    authDomain: 'stockcito-eb381.firebaseapp.com',
    storageBucket: 'stockcito-eb381.firebasestorage.app',
    measurementId: 'G-FS2WG3PBX2',
  );

}